import type { Metadata } from "next";
import "./globals.css";

// USING THESE GOOGLE FONTS
import {
    Afacad,
    Lato,
    Montserrat,
    DM_Sans,
    Manrope,
    Plus_Jakarta_Sans,
} from "next/font/google";

const lato400 = Lato({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-lato400",
});

const lato900 = Lato({
    weight: "900",
    subsets: ["latin"],
    variable: "--font-lato900",
});

const montserrat400 = Montserrat({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-montserrat400",
});

const afacad700 = Afacad({
    weight: "700",
    subsets: ["latin"],
    variable: "--font-afacad700",
});

const dmSans400 = DM_Sans({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-dmsans400",
});

const manrope400 = Manrope({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-manrope400",
});

const plusJakartaSans400 = Plus_Jakarta_Sans({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-plusJakartaSans400",
});

// METADATA FOR THE PAGE
export const metadata: Metadata = {
    title: "DevX Alpha",
    description: "Generated by create next app",
};

import { Navbar, Footer } from "@/components";
import SessionProvider from "@/components/SessionProvider";
import ToastProvider from "@/components/ToastProvider";
import ReduxProvider from "@/components/ReduxProvider";
import AuthSyncWrapper from "@/components/AuthSyncWrapper";

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={[
                lato400.variable,
                lato900.variable,
                montserrat400.variable,
                afacad700.variable,
                dmSans400.variable,
                manrope400.variable,
                plusJakartaSans400.variable,
            ].join(" ")}
        >
            <body className="bg-white text-black">
                <ReduxProvider>
                    <SessionProvider>
                        <AuthSyncWrapper>
                            <ToastProvider />
                            <Navbar />
                            {children}
                            <Footer />
                        </AuthSyncWrapper>
                    </SessionProvider>
                </ReduxProvider>
            </body>
        </html>
    );
}
